name: deploy-color-app

on:
  push:
    branches:
      - master
    paths:
      - 'color_app_project/**'

defaults:
  run:
    working-directory: color_app_project

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install --force
      - run: npm run build

      - run: aws s3 sync build s3://${{secrets.AWS_S3_BUCKET_NAME}}/color_app/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-3
